export {
  emailSchema,
  honeypotSchema,
  nameSchema,
  messageSchema,
  officeEmailSchema,
  optionalPhoneSchema,
  phoneSchema,
  slugSchema,
  sourcePathSchema,
  subjectSchema,
} from "@/lib/validations/common";
export {
  CAREER_FORM_KEYS,
  CONTACT_FORM_KEYS,
  CONTACT_OFFICE_OPTIONS,
  CONTACT_OFFICES,
  PRODUCT_FORM_KEYS,
  careerEnquirySchema,
  contactEnquirySchema,
  enquiryKindSchema,
  productEnquirySchema,
  projectEnquirySchema,
  staffEmailForOffice,
} from "@/lib/validations/enquiry";
export type {
  CareerEnquiry,
  CareerEnquiryInput,
  ContactEnquiry,
  ContactEnquiryInput,
  ContactOffice,
  ProductEnquiry,
  ProductEnquiryInput,
  ProjectEnquiry,
  ProjectEnquiryInput,
} from "@/lib/validations/enquiry";
